# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osirisService.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'osirisService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13osirisService.proto\x12\rosirisService\"!\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"2\n\x11UpdateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"-\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"6\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xba\x02\n\x04User\x12K\n\nCreateUser\x12 .osirisService.CreateUserRequest\x1a\x1b.osirisService.UserResponse\x12\x45\n\x07GetUser\x12\x1d.osirisService.GetUserRequest\x1a\x1b.osirisService.UserResponse\x12K\n\nUpdateUser\x12 .osirisService.UpdateUserRequest\x1a\x1b.osirisService.UserResponse\x12Q\n\nDeleteUser\x12 .osirisService.DeleteUserRequest\x1a!.osirisService.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osirisService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=38
  _globals['_CREATEUSERREQUEST']._serialized_end=71
  _globals['_GETUSERREQUEST']._serialized_start=73
  _globals['_GETUSERREQUEST']._serialized_end=106
  _globals['_UPDATEUSERREQUEST']._serialized_start=108
  _globals['_UPDATEUSERREQUEST']._serialized_end=158
  _globals['_DELETEUSERREQUEST']._serialized_start=160
  _globals['_DELETEUSERREQUEST']._serialized_end=196
  _globals['_USERRESPONSE']._serialized_start=198
  _globals['_USERRESPONSE']._serialized_end=243
  _globals['_DELETEUSERRESPONSE']._serialized_start=245
  _globals['_DELETEUSERRESPONSE']._serialized_end=299
  _globals['_USER']._serialized_start=302
  _globals['_USER']._serialized_end=616
# @@protoc_insertion_point(module_scope)
